# Generated by Django 3.2.8 on 2021-11-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image_discription',
        ),
    ]
